name = "SliceMap"
uuid = "82cb661a-3f19-5665-9e27-df437c7e54c8"
authors = ["Michael Abbott"]
version = "0.2.1"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
ForwardDiff = "0.8, 0.9, 0.10"
JuliennedArrays = "0.0.3, 0.2"
StaticArrays = "0.10, 0.11, 0.12"
Tracker = "0.2"
Zygote = "0.4"
ZygoteRules = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Zygote"]
